# Generated by Django 3.0.2 on 2020-09-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name_plural': 'Signup'},
        ),
        migrations.AddField(
            model_name='signup',
            name='image',
            field=models.ImageField(default='', upload_to='profile'),
        ),
    ]
